Updt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -72,19 +72,18 @@ jobs:
           dotnet-version: '6.0.x'
 
     - name: Extract Manifest ID from Choice
-            id: manifest_lookup
-            run: |
-            # The input string, e.g., 'SR2 v2020.10.23 (856213111485396824)'
-            CHOICE="${{ github.event.inputs.SR2Ver-ManifestID }}"
+        id: manifest_lookup
+        run: |
+        CHOICE="${{ github.event.inputs.SR2Ver-ManifestID }}"
 
-            MANIFEST_ID=$(echo "$CHOICE" | grep -oP '\((\d+)\)' | grep -oP '\d+')
+        MANIFEST_ID=$(echo "$CHOICE" | grep -oP '\((\d+)\)' | grep -oP '\d+')
 
-            if [ -z "$MANIFEST_ID" ]; then
-                echo "::error::Could not extract Manifest ID from '$CHOICE'"
-                exit 1
-            fi
-            echo "manifest_id=$MANIFEST_ID" >> $GITHUB_OUTPUT
-            shell: bash
+        if [ -z "$MANIFEST_ID" ]; then
+            echo "::error::Could not extract Manifest ID from '$CHOICE'"
+            exit 1
+        fi
+        echo "manifest_id=$MANIFEST_ID" >> $GITHUB_OUTPUT
+        shell: bash
 
       - name: 0. Update Version Constants in EntryPoint.cs ⚙️
         shell: bash
